/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcodemag;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.System.in;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author F
 */
public class Barcode extends javax.swing.JFrame {

    public String server = "";
    public String db = "";
    public String usr = "";
    public String pwd = "";

    public CampiDB aggSigillo;
    public String DbAct = "";

    public static MySqlAccess dao;

    /**
     * Creates new form Barcode
     */
    /**
     * *
     * File parametri c:\barcode\cfg.txt: LABEL server database user password
     */
    public Barcode() {
        initComponents();
        readConfig();
        lsig.setVisible(false);
        lqta.setVisible(false);
        tqta.setVisible(false);
        dao = new MySqlAccess(server, db, usr, pwd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bcode = new javax.swing.JTextField();
        lsig = new javax.swing.JLabel();
        lcod = new javax.swing.JLabel();
        ldes = new javax.swing.JLabel();
        llot = new javax.swing.JLabel();
        tqta = new javax.swing.JTextField();
        lqta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        bcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcodeActionPerformed(evt);
            }
        });

        lsig.setBackground(new java.awt.Color(255, 51, 51));
        lsig.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lsig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lcod.setBackground(new java.awt.Color(204, 204, 204));
        lcod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lcod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ldes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ldes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        llot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        llot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        tqta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tqta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tqta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tqtaActionPerformed(evt);
            }
        });

        lqta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lqta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcode, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lcod, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ldes, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lqta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(tqta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lsig, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(llot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcod, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsig, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tqta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lqta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Stampa Etichette [SIGILLO]");

        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 2, 24)); // NOI18N

        labn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(labn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(labn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcodeActionPerformed
        String id = bcode.getText();
        bcode.setText("");
        if ("S".equals(id.substring(0, 1))) {
            id = id.substring(1);
            try {
                leggiSigillo(id);
            } catch (SQLException ex) {
                Logger.getLogger(Barcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                CampiDB campi = dao.cscDecode(id);
                if (campi.isCk()) {
                    compilaCampi(campi);
                    inputQta("Inserire qta sigillo");
                    aggSigillo = campi;
                    DbAct = "ins";
                }
            } catch (SQLException ex) {
                Logger.getLogger(Barcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_bcodeActionPerformed

    private void tqtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tqtaActionPerformed
        // TODO add your handling code here:
        if (DbAct.equals("ins")) {
            try {
                dao.creaSigillo(aggSigillo, Integer.parseInt(tqta.getText()));
                if (aggSigillo.isCk()) {
                    leggiSigillo(Integer.toString(aggSigillo.getId()));
                    tqta.setText("");
                    tqta.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Barcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (DbAct.equals("upd")) {
            System.out.println("upd: " + aggSigillo.getId());

        }

    }//GEN-LAST:event_tqtaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barcode().setVisible(true);
            }
        });
    }

    private void leggiSigillo(String id) throws SQLException {
        CampiDB campi = dao.leggiSigillo(id);
        if (campi.isCk()) {
            compilaCampi(campi);
            if (campi.getQta() > 0) {
                lsig.setOpaque(false);
                inputQta("Inserire qta prelevata");
                aggSigillo = campi;
                DbAct = "upd";
            } else {
                lsig.setOpaque(true);
            }
        }
    }

    private void compilaCampi(CampiDB campi) {
        lcod.setText(campi.getCod());
        ldes.setText(campi.getDes());
        llot.setText("Lotto: " + campi.getLotto());
        lsig.setVisible(true);
        lsig.setText(Integer.toString(campi.getQta()));
    }

    private void inputQta(String msg) {
        lqta.setText(msg);
        bcode.setVisible(false);
        lqta.setVisible(true);
        tqta.setVisible(true);
        tqta.requestFocus();
    }

    private void readConfig() {
        try {
            BufferedReader br = new BufferedReader(new FileReader("c://barcode//cfg.txt"));
            labn.setText(br.readLine());
            server = br.readLine();
            db = br.readLine();
            usr = br.readLine();
            pwd = br.readLine();
            in.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(Barcode.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labn;
    private javax.swing.JLabel lcod;
    private javax.swing.JLabel ldes;
    private javax.swing.JLabel llot;
    private javax.swing.JLabel lqta;
    private javax.swing.JLabel lsig;
    private javax.swing.JTextField tqta;
    // End of variables declaration//GEN-END:variables
}
